# ? Puerto donde correrá nuestro servidor Java
server.port=8080

# ? Conexión a tu base de datos PostgreSQL (La que creamos en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/neofleet_db
spring.datasource.username=fleet_admin
spring.datasource.password=supersecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? Configuración de JPA (Para que Java entienda el SQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true