server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/neofleet_db
spring.datasource.username=fleet_admin
spring.datasource.password=supersecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true